### ISSUE TITLE
Move examples to a separate folder

### ISSUE THREAD

**Issue by Lonami** [vzccristian/pyro4bot#3]
The root folder has a lot of `*.py` and `*.json` files that are clearly usage examples. Consider moving all of these to an `examples/` so the structure remains clean, and things don't get mixed up.

**Comment by vzccristian** [comment]
Hi again Lonami,

Thanks for opening this issue. 

As you can see, we already work with a more organized structure. We mark this issue as closed. If you think it should not have closed because it has not been solved, please, let us know.

Greetings,

Cristian.

**Comment by Lonami** [comment]
I presume you're talking about https://github.com/vzccristian/pyro4bot/commit/61c76c3287bf2fe2bee6262107ec10ab12bde4d2. While some things were fixed, class names are now worse :). As a summary:

* `CONSTANT_VALUE`.
* `ClassName`.
* `variable_name`.
* `public_method`.
* `_private_method`.

**Comment by vzccristian** [comment]
Yes, you can read the name of the commit.
" Camelcase earring in sensors…"

Using camelcase in classes and not in files, causes the system to not work correctly.  This will be corrected soon.
